repos:
  - repo: https://github.com/lyz-code/yamlfix
    rev: f857ca370af3db7e5e181373d45c06a148fac3f8  # frozen: 1.19.1
    hooks:
      - id: yamlfix
        args: [--config-file, ./.config/yamlfix.toml]
  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: [--config-file, ./.config/yamllint.yaml, --strict]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/hadolint/hadolint
  #   rev: 57e1618d78fd469a92c1e584e8c9313024656623  # frozen: v2.14.0
  #   hooks:
  #     - id: hadolint-docker
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 1f1e8bf348ff38fc88619a38d3ca4d9c56abea49  # frozen: v0.16.5
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa  # frozen: v1.29.0
    hooks:
      - id: zizmor
        args: [--config, ./.config/zizmor.yml]
