services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark-py
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark-py
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    deploy:
      replicas: 2
  
  spark-job-sparkie:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - spark-master
    profiles:
      - spark-job-sparkie
